# Generated by Django 3.2.4 on 2021-06-08 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publisehd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
