# Generated by Django 3.2.4 on 2021-06-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_publisehd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publisehd',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publisehd',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='publisehd',
            new_name='published',
        ),
    ]
